var _app={},tab_counter=1,active_editors=[],active_editors_count=0,main_url="/html5_ide";
_app.base={_author:"Omar Ahmed Al-Safi",_version:"0.2 beta",project_id_global:project_id,get_version:function(a){return a},ajax_main_url:main_url+"/server/files_operations",ajax_load_file_url:main_url+"/server/load_file",ajax_save_file_url:main_url+"/server/save_file",ajax_preview_file:main_url+"/server/preview_file",ajax_load_all_code_bits:main_url+"/server/load_all_code_bits",ajax_code_bit_url:main_url+"/server/load_code_bit/",icons_path:main_url+"/img/"};
_app.contextmenu={open_btn:{separator_before:!1,separator_after:!1,label:"Open",action:function(a){var b=a.attr("id").split("_")[1];file_id="#"+a.attr("id");file_name=$(file_id).text();file_type=file_name.split(".")[1];_app.utility.initlize_new_tab(b,file_name,file_type)}},preview_btn:{separator_before:!1,separator_after:!1,label:"Preview",action:function(a){a=a.attr("id").split("_")[1];_app.utility.preview_file(a)}},edit_btn:{separator_before:!0,icon:!1,separator_after:!0,label:"Edit",action:!1,
submenu:{cut:{separator_before:!1,separator_after:!1,label:"Cut",action:function(a){this.cut(a)}},copy:{separator_before:!1,icon:!1,separator_after:!1,label:"Copy",action:function(a){this.copy(a)}},paste:{separator_before:!1,icon:!1,separator_after:!1,label:"Paste",action:function(a){this.paste(a)}}}},rename_btn:{separator_before:!1,separator_after:!1,label:"Rename",action:function(a){this.rename(a)}},remove_btn:{separator_before:!1,icon:!1,separator_after:!1,label:"Delete",action:function(a){this.is_selected(a)?
this.remove():this.remove(a)}},create_btn:{separator_before:!1,separator_after:!0,label:"Create",action:!1,submenu:{create_file:{seperator_before:!1,seperator_after:!1,label:"File",action:function(a){this.create(a,"last",{attr:{rel:"default"}})}},create_folder:{seperator_before:!1,seperator_after:!1,label:"Folder",action:function(a){this.create(a,"last",{attr:{rel:"folder"}})}}}},save_file_btn:{separator_before:!1,separator_after:!1,label:"Save",action:function(a){a=a.attr("id").split("_")[1];_app.utility.save_file(a)}},
load_file_menu:function(){return{open:this.open_btn,preview:this.preview_btn,ccp:this.edit_btn,rename:this.rename_btn,remove:this.remove_btn}},load_folder_menu:function(){return{create:this.create_btn,ccp:this.edit_btn,rename:this.rename_btn,remove:this.remove_btn}},load_drive_menu:function(){return{create:this.create_btn,edit:this.edit_btn}}};
_app.codebits={load_all_code_bits:function(a){$.ajax({url:_app.base.ajax_load_all_code_bits,dataType:"html",success:function(b){a(b)}})},load_code_bit:function(a,b){$.ajax({url:_app.base.ajax_code_bit_url+b,dataType:"html",success:function(b){a(b)}})}};
_app.utility={editor:null,get_project_id:function(){},open_editor:function(a,b){var c=document.getElementById("code_"+a);active_editors[active_editors_count]=new IdeEditor(c,{path:main_url+"/js/",searchMode:"popup"},"js"==b?{lineNumbers:!0,matchBrackets:!0,mode:"text/javascript"}:"css"==b?{lineNumbers:!0,mode:"text/css"}:{lineNumbers:!0,mode:"text/html",tabMode:"indent"});active_editors_count++},open_file:function(a,b,c){$.ajax({url:_app.base.ajax_load_file_url+"/"+_app.base.project_id_global+"/"+
a+"/",type:"POST",dataType:"html",success:function(d){var e=document.createElement("textarea");e.id="code_"+a;e.name="code_"+a;var f=document.createElement("div");f.className="editor";f.id="editor_"+a;f.appendChild(e);document.getElementById(b).appendChild(f);document.getElementById("code_"+a).innerHTML=d;_app.utility.open_editor(a,c)}})},save_file:function(a,b,c){$.ajax({url:_app.base.ajax_save_file_url+"/"+_app.base.project_id_global+"/"+b+"/",type:"POST",data:{data:c},dataType:"json",success:function(b){a(b)}})},
preview_file:function(a){$.ajax({url:_app.base.ajax_preview_file+"/"+a+"/",type:"POST",dataType:"html",success:function(a){window.open(main_url+"/public/"+project_hash+"/"+a,"_blank")}})},open_preview_window:function(){},initlize_new_tab:function(a,b,c){var d=!1,e=null;$("#tabs ul li a").each(function(){$(this).attr("rel")==a&&(d=!0,e=$(this).attr("href"))});if(d)b=e.split("#tabs-")[1],$("#tabs").tabs("select",b);else{tab_counter+=1;$("#tabs").tabs("add","#tabs-"+tab_counter,b);var f="#tabs-"+tab_counter;
$("#tabs ul li a").each(function(){$(this).attr("href")==f&&$(this).attr("rel",a)});_app.utility.open_file(a,"tabs-"+tab_counter,c)}}};
$(function(){$("#left_col").resizable({handles:"e",minWidth:350,maxWidth:600});$("#tabs").tabs({closable:!0,add:function(a,b){$("#tabs").tabs("select","#"+b.panel.id)}});$("#files_tree").bind("before.jstree",function(a,b){$("#alog").append(b.func+"<br />")}).jstree({plugins:"themes,json_data,ui,crrm,cookies,dnd,search,types,hotkeys,contextmenu".split(","),themes:{theme:"apple",url:main_url+"/css/jstree/apple/style.css"},json_data:{ajax:{url:_app.base.ajax_main_url,data:function(a){return{operation:"get_children",
id:a.attr?a.attr("id").replace("node_",""):_app.base.project_id_global,request_type:a.attr?"normal_request":"get_tree_first_load",project_id:_app.base.project_id_global}}}},contextmenu:{items:function(a){return"default"==a.attr("rel")?_app.contextmenu.load_file_menu():"folder"==a.attr("rel")?_app.contextmenu.load_folder_menu():_app.contextmenu.load_drive_menu()}},search:{ajax:{url:_app.base.ajax_main_url,data:function(a){return{operation:"search",search_str:a}}}},types:{max_depth:-2,max_children:-2,
valid_children:["drive"],types:{"default":{valid_children:"none",icon:{image:_app.base.icons_path+"file.png"}},folder:{valid_children:["default","folder"],icon:{image:_app.base.icons_path+"folder.png"}},drive:{valid_children:["default","folder"],icon:{image:_app.base.icons_path+"root.png"},start_drag:!1,move_node:!1,delete_node:!1,remove:!1,rename:!1},project:{valid_children:["default","folder"],icon:{image:_app.base.icons_path+"root.png"},start_drag:!1,move_node:!1,delete_node:!1,remove:!1,rename:!1}}},
ui:{initially_select:["node_4"]},core:{initially_open:["node_69","node_3"]}}).bind("create.jstree",function(a,b){$.post(_app.base.ajax_main_url,{operation:"create_node",id:b.rslt.parent.attr("id").replace("node_",""),position:b.rslt.position,title:b.rslt.name,type:b.rslt.obj.attr("rel"),project_id:_app.base.project_id_global},function(a){a.status?$(b.rslt.obj).attr("id","node_"+a.id):$.jstree.rollback(b.rlbk)})}).bind("remove.jstree",function(a,b){b.rslt.obj.each(function(){$.ajax({async:!1,type:"POST",
url:_app.base.ajax_main_url,data:{operation:"remove_node",id:this.id.replace("node_",""),project_id:_app.base.project_id_global},success:function(a){a.status||b.inst.refresh()}})})}).bind("rename.jstree",function(a,b){$.post(_app.base.ajax_main_url,{operation:"rename_node",id:b.rslt.obj.attr("id").replace("node_",""),title:b.rslt.new_name,project_id:_app.base.project_id_global},function(a){a.status||$.jstree.rollback(b.rlbk)})}).bind("move_node.jstree",function(a,b){b.rslt.o.each(function(a){$.ajax({async:!1,
type:"POST",url:_app.base.ajax_main_url,data:{operation:"move_node",id:$(this).attr("id").replace("node_",""),ref:-1===b.rslt.cr?1:b.rslt.np.attr("id").replace("node_",""),position:b.rslt.cp+a,title:b.rslt.name,copy:b.rslt.cy?1:0,project_id:_app.base.project_id_global},success:function(a){a.status?($(b.rslt.oc).attr("id","node_"+a.id),b.rslt.cy&&$(b.rslt.oc).children("UL").length&&b.inst.refresh(b.inst._get_parent(b.rslt.oc))):$.jstree.rollback(b.rlbk);$("#analyze").click()}})})}).delegate("a","dblclick",
function(){var a=$(this).parent().attr("id").split("_")[1],b=$(this).parent().attr("rel"),c=$(this).html().split('<ins class="jstree-icon">&nbsp;</ins>')[1],d=c.split(".")[1];"default"==b&&_app.utility.initlize_new_tab(a,c,d)})});