function IdeEditor(a,b,c){this.initialize(a,b,c)}
IdeEditor.prototype={initialize:function(a,b,c){this.textarea=a;this.options=b;this.setDefaults(this.options,{searchMode:"popup",path:"js",buttons:"save,search,code_bits,undo,redo,jump,reindentSelection,reindent,preview".split(",")});this.buttonDefs={save:["Save","save",this.options.path+"../images/editor_icons/document-save-as2.png",this.save],search:["Search/Replace","find_replace_popup",this.options.path+"../images/editor_icons/edit-find-replace2.png",this.find_replace_popup],searchClose:["Close",
"find_replace_popup_close",this.options.path+"../images/silk/cancel.png",this.find_replace_popup_close],searchDialog:["Search/Replace","find_replace_window",this.options.path+"../images/silk/find.png",this.find_replace_window],undo:["Undo","undo",this.options.path+"../images/editor_icons/edit-undo2.png",this.undo],redo:["Redo","redo",this.options.path+"../images/editor_icons/edit-redo2.png",this.redo],jump:["Jump to line #","jump",this.options.path+"../images/editor_icons/go-jump2.png",this.jump],
reindentSelection:["Reformat selection","reindentSelect",this.options.path+"../images/editor_icons/format-indent-more2.png",this.reindentSelection],reindent:["Reformat whole document","reindent",this.options.path+"../images/editor_icons/format-justify-left2.png",this.reindent],about:["About CodeMirror-UI","about",this.options.path+"../images/editor_icons/dialog-information2.png",this.about],code_bits:["CodeBits","codebits",this.options.path+"../images/editor_icons/preferences-system2.png",this.codebits],
preview:["Preview","preview",this.options.path+"../images/editor_icons/text-html2.png",this.preview]};this.home=document.createElement("div");this.home.className="test";this.textarea.parentNode.insertBefore(this.home,this.textarea);this.self=this;_this=this;var d=this.editorChanged.bind(this);c.onChange=c.onChange?function(){c.onChange();d()}:d;this.mirror=mir=CodeMirror.fromTextArea(this.textarea,c);this.initButtons();this.editor_changed=!1;"inline"==this.options.searchMode?this.initFindControl():
"popup"==this.options.searchMode&&this.initPopupFindControl();this.undoButton&&this.addClass(this.undoButton,"inactive");this.redoButton&&this.addClass(this.redoButton,"inactive")},setDefaults:function(a,b){for(var c in b)a.hasOwnProperty(c)||(a[c]=b[c])},toTextArea:function(){this.home.parentNode.removeChild(this.home);this.mirror.toTextArea()},initButtons:function(){this.buttonFrame=document.createElement("div");this.buttonFrame.className="codemirror-ui-clearfix codemirror-ui-button-frame";this.home.appendChild(this.buttonFrame);
for(var a=0;a<this.options.buttons.length;a++){var b=this.buttonDefs[this.options.buttons[a]];this.addButton(b[0],b[1],b[2],b[3],this.buttonFrame)}},createFindBar:function(){var a=document.createElement("div");a.className="codemirror-ui-find-bar";this.findString=document.createElement("input");this.findString.type="text";this.findString.size=8;this.findButton=document.createElement("input");this.findButton.type="button";this.findButton.value="Find";this.findButton.onclick=function(){this.find()}.bind(this);
this.connect(this.findString,"keyup",function(a){13==a.keyCode?this.find(this.mirror.getCursor(!1)):""==!this.findString.value&&this.find(this.mirror.getCursor(!0));this.findString.focus()}.bind(this));var b=document.createElement("label");b.title="Regular Expressions";this.regex=document.createElement("input");this.regex.type="checkbox";this.regex.className="codemirror-ui-checkbox";b.appendChild(this.regex);b.appendChild(document.createTextNode("RegEx"));var c=document.createElement("label");c.title=
"Case Sensitive";this.caseSensitive=document.createElement("input");this.caseSensitive.type="checkbox";this.caseSensitive.className="codemirror-ui-checkbox";c.appendChild(this.caseSensitive);c.appendChild(document.createTextNode("A/a"));this.replaceString=document.createElement("input");this.replaceString.type="text";this.replaceString.size=8;this.connect(this.replaceString,"keyup",function(a){13==a.keyCode&&this.replace()}.bind(this));this.replaceButton=document.createElement("input");this.replaceButton.type=
"button";this.replaceButton.value="Replace";this.replaceButton.onclick=this.replace.bind(this);var d=document.createElement("label");d.title="Replace All";this.replaceAll=document.createElement("input");this.replaceAll.type="checkbox";this.replaceAll.className="codemirror-ui-checkbox";d.appendChild(this.replaceAll);d.appendChild(document.createTextNode("All"));a.appendChild(this.findString);a.appendChild(this.findButton);a.appendChild(c);a.appendChild(b);a.appendChild(this.replaceString);a.appendChild(this.replaceButton);
a.appendChild(d);return a},initPopupFindControl:function(){var a=this.createFindBar();this.popupFindWrap=document.createElement("div");this.popupFindWrap.className="codemirror-ui-popup-find-wrap";this.popupFindWrap.appendChild(a);a=this.buttonDefs.searchClose;this.addButton(a[0],a[1],a[2],a[3],this.popupFindWrap);this.buttonFrame.appendChild(this.popupFindWrap)},initFindControl:function(){this.buttonFrame.appendChild(this.createFindBar())},find:function(a){null==a&&(a=this.mirror.getCursor());var b=
this.findString.value;null==b||""==b?alert("You must enter something to search for."):(this.regex.checked&&(b=RegExp(b)),this.cursor=this.mirror.getSearchCursor(b,a,!this.caseSensitive.checked),(a=this.cursor.findNext())?this.mirror.setSelection(this.cursor.from(),this.cursor.to()):confirm("No more matches.  Should we start from the top?")&&(this.cursor=this.mirror.getSearchCursor(b,0,!this.caseSensitive.checked),(a=this.cursor.findNext())?this.mirror.setSelection(this.cursor.from(),this.cursor.to()):
alert("No matches found.")))},replace:function(){if(this.replaceAll.checked)for(var a=this.mirror.getSearchCursor(this.findString.value,this.mirror.getCursor(),!this.caseSensitive.checked);a.findNext();)this.mirror.replaceRange(this.replaceString.value,a.from(),a.to());else this.mirror.replaceRange(this.replaceString.value,this.cursor.from(),this.cursor.to()),this.find()},initWordWrapControl:function(){var a=document.createElement("div");a.className="codemirror-ui-wrap";var b=document.createElement("label");
this.wordWrap=document.createElement("input");this.wordWrap.type="checkbox";this.wordWrap.checked=!0;b.appendChild(this.wordWrap);b.appendChild(document.createTextNode("Word Wrap"));this.wordWrap.onchange=this.toggleWordWrap.bind(this);a.appendChild(b);this.buttonFrame.appendChild(a)},toggleWordWrap:function(){this.wordWrap.checked?this.mirror.setTextWrapping("nowrap"):this.mirror.setTextWrapping("")},addButton:function(a,b,c,d,f){var e=document.createElement("a");e.className="codemirror-ui-button "+
b;e.title=a;e.func=d.bind(this);e.onclick=function(a){a.target.func();return!1}.bind(this,d);a=document.createElement("img");a.src=c;a.border=0;a.func=d.bind(this);e.appendChild(a);f.appendChild(e);"undo"==b&&(this.undoButton=e);"redo"==b&&(this.redoButton=e)},classNameRegex:function(a){return RegExp("(.*) *"+a+" *(.*)")},addClass:function(a,b){a.className.match(this.classNameRegex(b))||(a.className+=" "+b)},removeClass:function(a,b){var c=a.className.match(this.classNameRegex(b));c&&(a.className=
c[1]+" "+c[2])},changeName:function(){var a=this.textarea.id.split("code_")[1];$("#tabs ul li a").each(function(){$(this).attr("rel")==a&&$(this).find("span").append("*")})},editorChanged:function(){if(this.mirror){this.editor_changed||(this.changeName(),this.editor_changed=!0);var a=this.mirror.historySize();0<a.undo?this.removeClass(this.undoButton,"inactive"):this.addClass(this.undoButton,"inactive");0<a.redo?this.removeClass(this.redoButton,"inactive"):this.addClass(this.redoButton,"inactive")}},
undo:function(){this.mirror.undo()},redo:function(){this.mirror.redo()},replaceSelection:function(a){this.mirror.replaceSelection(a);this.searchWindow.focus()},raise_search_window:function(){this.searchWindow.focus()},find_replace_window:function(){null==this.searchWindow&&(this.searchWindow=window.open(this.options.path+"find_replace.html","mywindow","scrollbars=1,width=400,height=350,modal=yes"),this.searchWindow.codeMirrorUI=this);this.searchWindow.focus()},find_replace_popup:function(){this.popupFindWrap.className=
"codemirror-ui-popup-find-wrap active";this.findString.focus()},find_replace_popup_close:function(){this.popupFindWrap.className="codemirror-ui-popup-find-wrap"},preview:function(){file_id=this.textarea.id.split("code_")[1];_app.utility.preview_file(file_id)},jump:function(){var a=prompt("Jump to line:","");a&&!isNaN(Number(a))&&(this.mirror.setCursor(Number(a),0),this.mirror.setSelection({line:Number(a),ch:0},{line:Number(a)+1,ch:0}),this.mirror.focus())},reindent:function(){for(var a=this.mirror.lineCount(),
b=0;b<a;b++)this.mirror.indentLine(b)},codebits:function(){var a=document.getElementById("code_bits_menu"),b=this.mirror;a?this.home.removeChild(a):(a=document.createElement("div"),a.id="code_bits_menu",this.home.appendChild(a),_app.codebits.load_all_code_bits(function(a){$("#code_bits_menu").html(a);$("#code_bits_menu").find("li:has(ul)").bind("mouseover",function(){$(this).children("ul").show()}).bind("mouseleave",function(){$(this).children("ul").hide()});$("#code_bits_menu").bind("mouseleave",
function(){$(this).remove()});$("#code_bits_menu").find("li:not(:has(ul))").click(function(){code_id=$(this).attr("id");_app.codebits.load_code_bit(function(a){b.somethingSelected()?b.replaceSelection(a):b.replaceRange(a,b.getCursor())},code_id)})}))},about:function(){},get_value:function(){return this.mirror.getValue()},reindentSelection:function(){this.mirror.getCursor();for(var a=this.mirror.getCursor(!0).line,b=this.mirror.getCursor(!1).line;a<=b;a++)this.mirror.indentLine(a)},save:function(){data=
this.get_value();editor_changed=this.editor_changed;var a=this.textarea.id.split("code_")[1];_app.utility.save_file(function(b){b.status&&editor_changed&&$("#tabs ul li a").each(function(){$(this).attr("rel")==a&&(filename=$(this).find("span").html().split("*")[0],$(this).find("span").html(filename),_this.editor_changed=!1)})},a,data)},connect:function(a,b,c,d){if("function"==typeof a.addEventListener){if(a.addEventListener(b,c,!1),d)return function(){a.removeEventListener(b,c,!1)}}else if(a.attachEvent("on"+
b,c),d)return function(){a.detachEvent("on"+b,c)}}};Function.prototype.bind=function(a){var b=this;return function(){return b.apply(a,arguments)}};